# -*- coding: utf-8 -*-
# Controller generated by Typus, use it to extend admin functionality.
class Admin::SourcesController < Admin::MasterController #ApplicationController
  
  
  def set_categories
    params[:id]=params[:source][:id]
    s=Source.find_by_id(params[:id])
    s.set_categories(params[:categories])

    export
    #  redirect_to :action => :index
    render :action => :export
  end
  
  def export
    s=Source.find_by_id(params[:id])
    
    
    # Экспорт записей, имеющих категорию
    @exported_records=s.export_to_catalog
    
    # Сбор вспомогательных данных
    @updated_records=s.results.updated.count
    @category_for_select = Category.all_for_select
    @new_categories = s.unprocessed_categories
#    @result_categories = s.result_categories
    @source=s
    
  end
  
  def export_all
    Source.find(:all).map { |s| s.export_to_catalog}
  end


=begin

  ##
  # You can overwrite and extend Admin::MasterController with your methods.
  #
  # Actions have to be defined in <tt>config/typus/application.yml</tt>:
  #
  #   Source:
  #     actions:
  #       index: custom_action
  #       edit: custom_action_for_an_item
  #
  # And you have to add permissions on <tt>config/typus/application_roles.yml</tt> 
  # to have access to them.
  #
  #   admin:
  #     Source: create, read, update, destroy, custom_action
  #
  #   editor:
  #     Source: create, read, update, custom_action_for_an_item
  #

  def index
  end

  def custom_action
  end

  def custom_action_for_an_item
  end

=end

end
