# Typus Models Configuration File
#
# Use the README file on the same folder as this file as a reference to
# customize this file to your needs.


City:
  fields:
    list: name, ctype, prefix, is_prefix_owner
    form: ctype, name, prefix, is_prefix_owner
    show: id, ctype, name, prefix, is_prefix_owner
    options:
      selectors: ctype
  actions:
    edit: show
  order_by:
  filters: ctype
  search: name, prefix
  options:
    default_action_on_item: show
  application: 8352.info
  description:

TelefonFederal:
  fields:
    list: operator, federal, city
    form: federal, city, operator
    show: federal, city, operator
  actions:
    index: check_number
    edit: check_number
  order_by: operator, federal
  relationships: 
  filters: operator
  options:
    per_page: 50
  search: federal, city, operator
  application: 8352.info
  description:

TelefonRename:
  fields:
    list: oldphone, newphone, rename_date
    form: oldphone, newphone, rename_date
    show: oldphone, newphone, rename_date
  actions:
    index: check_number
    edit: check_number
  order_by: oldphone, newphone
  relationships: 
  filters: 
  options:
    per_page: 50
  search: oldphone, newphone
  application: 8352.info
  description:


Tag:
  fields:
    list: name, is_primary, taggings #,  taggings_count
    form: name, is_primary, description, taggings_count
    show: id, name, is_primary, description, taggings_count
  actions:
    index:
    edit:
  order_by: name
  relationships: taggings, tags_synonyms
  filters: is_primary
  options:
    per_page: 50
  search: name
  application: Tags
  description:

TagsSynonym:
  fields:
    list: name, tag
    form: name, tag
    show: name, tag
  actions:
    index:
    edit:
  order_by: name
  filters:
  options:
    per_page: 50
  search: name
  application: Tags
  description:


Tagging:
  fields:
    list: id, tag, taggable_type, taggable
    form: tag, taggable_id, taggable_type
    show: id, created_at, updated_at, tag, taggable, taggable_id, taggable_type
  actions:
    index:
    edit:
  order_by: 
  options:
    per_page: 50
  relationships: tag
  filters: 
  search: tag
  application: Tags
  description:






# APPLICATION:
#
# Company catalog
#

Category:
  fields:
    list: name, parent, position, tag_list #companies_count, position, hidden
    form: parent, name, position, tag_list, description
    show: id, name, description, tag_list, companies_count, position, children_count, ancestors_count, descendants_count, hidden, parent
  actions:
    index:
    edit: show
  order_by: parent_id, position
#  relationships: children #companies #, parent, children #, 
  options:
    per_page: 30
  filters:
  relationships: tags
  search: name
  application: Company catalog
  description: Основные категории компаний


Company:
  fields:
    list: name, results_count, tag_list, category
    form: name, inn, address, site, tag_list, director, description, working_time
    show: id, results_count, name, tag_list, inn, address, site, director, description, working_time, sources, created_at, updated_at, pending, dump, category
  actions:
    index:
    edit:
  order_by:
  relationships: category, emails, phones, results, tags
  filters: category, tag
  options:
    per_page: 50
  search: name, address
  application: Company catalog
  description: Каталог компаний

Email:
  fields:
    list: id, email, person, department, company
    form: email, person, department, company
    show: id, email, person, department, company
  actions:
    index:
    edit:
  order_by:
  relationships: company
  filters:
  options:
    per_page: 30
  search:
  application: Company catalog
  description:


Phone:
  fields:
    list: id, number, company, person, department, description
    form: number, person, department, working_time, description, short_code, company
    show: id, number, person, department, working_time, description, short_code, created_at, updated_at, company
  actions:
    index:
    edit:
  order_by:
  relationships: company
  filters:
  search: number, person, departmend
  options:
    selectors: state
    per_page: 30
  application: Company catalog
  description:





# APPLICATION:
#
# Company grabber
#

Link:
  fields:
    list: id, name, url, is_follow, links_count, source, parent
    form: name, url, is_follow, links_count, source, parent
    show: id, name, url, is_follow, links_count, created_at, updated_at, source, parent
  actions:
    index:
    edit:
  order_by:
  relationships: children, parent, results, source
  filters:
  search:
  application: Company grabber
  description:


ResultCategory:
  fields:
    list: category_name, category, tag_list, source_id
    show: id, category_name, category, tag_list, source_id
    form: category_name, category, tag_list, source
#    options: 
#      templates:
#        category_id: category
  actions:
    index:
    show: 
    exit:
  order_by: category_name
  filters:
  options:
    per_page: 30
  relationships: tags
  search: category_name
  application: Company grabber
  description:

Source:
  fields:
    list: target_url, grabber_name, results_count, ad_results_count
    form: target_url, grabber_name
    show: target_url, id, results_count, ad_results_count, grabber_name, created_at, updated_at
  actions:
    edit: show
    show: import_results
#, reset_imported_categories, reset_imported_companies
  order_by:
  relationships: result_categories #, results #links, results
  filters:
  search:
  options:
    default_action_on_item: show
  application: Company grabber
  description:

Result:
  fields:
    list: category_name, name, address, state, importer_state
    form: name, address, phones, email, site_url, result_category, category_name, work_time, other_info, raw_html, company, is_checked, state, importer_state
#, link
    show: id, name, address, phones, email, site_url, category_name, work_time, other_info, raw_html, is_checked, state, importer_state, created_at, updated_at, link, company, source
    options:
      selectors: state
  actions:
    index:
    edit:
  order_by: category_name, name
  options:
    selectors: state
    per_page: 30
#  relationships: company, link
  filters: aasm_state, is_removed
  search: category_name, name, address, phones, email, site_url
  application: Company grabber
  description:

