* TODO Экспорт данных [0%]
	SCHEDULED: <2009-07-05 Вск> DEADLINE: <2009-07-10 Птн> 
	
	1) [ ] Устанавливаем соответствие категорий по указанному источнику.
				 Выбираем все встречаемые названия категорий и ищем их соответсвия
				 в cat2sourcecat (таблицу надо создать). Если такой записи в cat2sourcecat нет,
				 даем возомжность оператору создать ее.
				 
	2) [ ] [0/4] Далее по каждой записи results указанного источника с флагом
				 is_updated и not need_human
				 
		 1) [ ] Устанавливаем короткое название, сохраняем его в result.short_name
						чтобы постоянно не определять. result.short_name=companies.name а result.name=companies.full_name.
						Можно переименовать в companies чтобы не путаться дальше.
		 2) [ ] Нормализуем адрес в вид: (Индекс) Город, Улица, дом, офис; другой_адрес,
						сохраняем его в result.normal_addresses
		 3) [ ] Определяем категорию на основе cat2sourcecat.
		 4) [ ] Добавляем компании по телефону, названию, адресу.
						- Если ok ставим result.is_update='f', если нет
							result.need_human='t'

	3) [ ] Тесты
				 
		 1) [ ] Нормализация адреса
		 2) [ ] Установка короткого имени
		 3) [ ] Есть новые категории
		 4) [ ] Удачно добавляем новую компанию
		 5) [ ] Удачно изменяем сущесвтующую компанию
		 6) [ ] Не можем обновить компанию (need_human)
						
* Админка каталога [0%]
 - [ ] Автоматическое закрытие поля компании при изменении attr_closed
 - [ ] need_human='t' и attr_freshed если есть поля которые закрыты
			 для обновления (attr_closed)
 - [ ] непереносимые организации и категории
			 помечать организации (наверное в results) и категорий (no_follow),
			 которые автоматически не вносятся в каталог
 - [ ] добавление компании пользователем или админом
* Поиск по результатам и категории [%]
* Каталог веб-сайтов
* Рейтинги и отзывы об организаци
